### ISSUE TITLE
The V8 platform used by this instance of Node does not support creating Workers

### ISSUE THREAD

**Issue by AwesomeNameMan** [tuananh/camaro#116]
**Describe the bug**
Updated from camaro 5.0.3 to 6 (6.0.3). Using camaro with electron to parse many XML strings. 
After the update electron crashes with the following error:

**The V8 platform used by this instance of Node does not support creating Workers**

**Minimal Script To Reproduce**

```
import { ready, transform } from 'camaro';

await ready();
result = await transform(files[fileName], template);
```

**Expected behavior**
Camaro not breaking my electron app.

- camaro version: 6.0.3
- Node version: v12.18.3
- Operating system: Windows 10 Version1909 (Build 18363.900)

**Comment by tuananh** [comment]
Looks like it's similar to this https://github.com/electron/electron/issues/18540 but lemme dig deeper into this. I've never use Electron before.

**Comment by AwesomeNameMan** [comment]
Thanks for the quick reply, tuananh!

Here some more info about the environment:

* electron version: 9.2.1 (had version 7.x.x before, but same behavior)

I'm distributing the camaro.wasm to the app after build and I've seen you added a worker.js with v6, which seems to break the electron app. As far as I know, electron uses his own node & V8 engine version.

**Comment by kentico-ericd** [comment]
I'm also having an issue that might be related. I'm writing a Zapier CLI application and started getting this error immediately after trying to call `transform()`

> Error: Cannot find module '/node_modules/piscina/dist/src/worker.js'

**Comment by tuananh** [comment]
@kentico-ericd what node / camaro version are you using?

**Comment by kentico-ericd** [comment]
I tried

- camaro 6.0.3
- node 10.22.0

Does it require node >=12? I think it might have been an issue with `zapier-platform-core` actually- if so, sorry for polluting the thread and I'll check with them :)

**Comment by AwesomeNameMan** [comment]
Workers should be stable with node >= 12.

@tuananh is it maybe possible to make the usage of workers for camaro optional? This could help with different environments and people can't argue about a lack in performance when workers are not in use.

**Comment by tuananh** [comment]
I might as well do that :)

**Comment by tuananh** [comment]
Fixed by #122

**Comment by AwesomeNameMan** [comment]
Problem still occurs for me with the following versions:

- camaro 6.1.0
- Electron 10.1.3

**The V8 platform used by this instance of Node does not support creating Workers**

**Comment by fabiospampinato** [comment]
Stil happening v12

**Comment by tuananh** [comment]
@AwesomeNameMan @fabiospampinato do you have minimal project so that I can try? I'm not very familiar with Electron.

**Comment by fabiospampinato** [comment]
This should reproduce it:

```sh
npm i ripread
```

And then:

```js
const ripread = require ( 'ripread' );

ripread ( ['/foo/bar'] );
```

**Comment by fabiospampinato** [comment]
Oh sorry I thought we were in electron's repo here 🤦‍♂️ my bad. You can probably reproduce the issue by running this library inside Electron's renderer process.

**Comment by AwesomeNameMan** [comment]
Hi tuananh,

any news here?

**Comment by tuananh** [comment]
Sorry i didn't have bandwidth for tis project lately. could you rollback to v3 where worker isn't used yet?

**Comment by absir1949** [comment]
@tuananh  i use camaro 3.0.19 There are still problems.
```
 error: \\?\C:\Users\cd\AppData\Local\Temp\3809f2b1-9563-44e0-8d63-6b5673ffc4d6.tmp.node is not a valid Win32 application.
```
- camaro 6.1.0,6.2,5.0
- Electron 11.5
- node 12.18.3

**Comment by kiwirm** [comment]
I am having a similar problem trying to use the package in a Next.js server action:
```
⨯ uncaughtException: [Error: Cannot find module '.../.next/server/vendor-chunks/worker.js'] {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}```
